### PR TITLE
Feature/stories page

### PR DESCRIPTION
**Pull request by tandebnath**

### CODE REVIEW

**Comment by lasyaneti** [comment]
Looks great 🎊 !!! We need to update the **nav bar** though

Also some images are shrinking weirdly on my monitor 
image

**Comment by tandebnath** [comment]
1. Updated the navbar
2. Potentially fixed image shrinking issue

**Review by nrking0 — DISMISSED** [review]
Looks good. Great job! I have some ideas that we can talk about adding another way to navigate to the page from the home page, but this looks good to merge!

**Comment by lasyaneti** [comment]
lgtm! small nit - ashay and miranda's profile pictures are compressing horizontally on my iphone and laptop. maybe you can crop their images to 1:1 ratio so it doesnt? not sure if it looks normal on other devices

**Comment by tandebnath** [comment]
@lasyaneti the above issue should be fixed now

**Pull request merged**
